package com.cblue.common;

public class Constants
{
	  public static final String AAA_SERVICE_URL = "http://w3a.huagu.com";
	  public static final String APKNAME = "HugGuCaiJing";
	  public static final int ASYNC_GET_TYPE = 3;
	  public static final int ASYNC_POST_TYPE_NO_WRITE = 2;
	  public static final int ASYNC_POST_TYPE_WRITE_XML = 1;
	  public static final int AUTO_REFRESH_OFF = 255;
	  public static final int AUTO_REFRESH_ON = 6000;
	  public static final int CHOICE_TEXT_SIZE = 18;
	  public static final String CHSTOCK_LOGIN_INFO = "提供一键式选股功能，便于用户迅速根据风险偏好等选择到适合投资风格的股票。依据基本分析学派、技术分析学派的投资理论，采用基本分析法、技术分析法和证券组合分析法的主要研究分析手段，以实时、盘后为两大时间维度，融合个股诊断和交易时机，构建选股和决策平台，从多维视角发掘和把握投资机会，包括模型选股、技术指标选股、统计指标选股和DDE决策选股四大模块。";
	  public static final String CHSTOCK_MODEL_NAME = "模型选股";
	  public static final String CH_STOCK_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/pzd.xml";
	  public static final String CMD_KLINE = "KLINE";
	  public static final String CMD_MARKET = "HQ";
	  public static final String CMD_MARKET2 = "HQ2";
	  public static final String CMD_MARKET2_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=HQ2&CODE=";
	  public static final String CMD_MARKET2_URL_IP_PORT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=HQ2&CODE=";
	  public static final String CMD_MARKET_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=HQ&CODE=";
	  public static final String CMD_MARKET_URL_IP_PORT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=HQ&CODE=";
	  public static final String CMD_MFTP = "MFTP";
	  public static final String CMD_MINI = "ZXG_MINI";
	  public static final String CMD_ORDER_QUEUE = "ORDER_QUEUE";
	  public static final String CMD_ORDER_QUEUE_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=ORDER_QUEUE&CODE=";
	  public static final String CMD_ORDER_QUEUE_URL_F5_IP_PORT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=ORDER_QUEUE&CODE=";
	  public static final String CMD_PARAM = "/Quote.dll?USER=XUYJ?CMD=";
	  public static final String CMD_SEARCH = "SEARCH";
	  public static final String CMD_SORT = "SORT";
	  public static final String CMD_TICK = "TICK";
	  public static final String CMD_TICK_L2 = "TICK_L2";
	  public static final String CMD_TICK_L2_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=TICK_L2&CODE=";
	  public static final String CMD_TICK_L2_URL_F5_IP_PORT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=TICK_L2&CODE=";
	  public static final String CMD_TICK_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=TICK&CODE=";
	  public static final String CMD_TICK_URL_F5_IP_PORT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=TICK&CODE=";
	  public static final String CMD_ZST = "ZST_L2";
	  public static final String CMD_ZST_LEVEL1 = "ZST";
	  public static final String CMD_ZXG = "ZXG";
	  public static final int CUSTOMER_DOWNLOADING = 0;
	  public static final String DDE_LOGIN_INFO = "DDE是根据level-2高速行情及逐单还原技术，对主力大单进行实时监测并指标化的决策体系。主要包括DDX、DDY、DDZ三大指标。DDX为大单买入净量占流通盘的比例，显示每日大单的净买入力度；DDY为每日买入大单成交量和卖出大单成交量的差占笔数化流通盘的比例；DDZ为大单成交量的差值,反映大资金的买入强度。DDE决策选股就是系统分别根据当日的DDX、DDY、DDZ值选取的排名前十的股票。";
	  public static final String DDE_MODEL_NAME = "DDE决策选股";
	  public static final String DDE_STOCK = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=DDE_SORT&amp;CODE=";
	  public static final int DEFAULT_DOWNLOADING = 1;
	  public static final int DEFAULT_TEXT_SIZE = 16;
	  public static final int DIALOG_ACCOUNT_ERROR = 50003;
	  public static final int DIALOG_COMMUNICATION = 11;
	  public static final int DIALOG_DOWNLOADING = 1;
	  public static final int DIALOG_NETWORK_ERROR = 2;
	  public static final int DIALOG_NEW_CONFIRM_INVALID = 8;
	  public static final int DIALOG_NEW_CONFIRM_NOT_EQUAL = 9;
	  public static final int DIALOG_NOTICE = 19;
	  public static final int DIALOG_NOT_ACCEPT_PROTOCOL = 5;
	  public static final int DIALOG_NUMBERERROR = 4;
	  public static final int DIALOG_NUMBERHINT = 3;
	  public static final int DIALOG_OLDPWD_INVALID = 7;
	  public static final int DIALOG_PWD_ERROR = 50008;
	  public static final int DIALOG_PWD_INVALID = 60004;
	  public static final int DIALOG_PWD_NOT_REGISTERED = 50005;
	  public static final int DIALOG_RESET_ERROR = 50004;
	  public static final int DIALOG_STOCK = 103;
	  public static final int DIALOG_STOCKDIAGNOSIS_NO_SUPPORT = 18;
	  public static final int DIALOG_STOCK_CODE_EMPTY = 16;
	  public static final int DIALOG_STOCK_CODE_NOT_EXITS = 14;
	  public static final int DIALOG_STOCK_INCLUDE_SPECIAL = 17;
	  public static final int DIALOG_TEXT_SIZE = 18;
	  public static final int DIALOG_WARNING_ADD = 100;
	  public static final int DIALOG_WARNING_DEL = 102;
	  public static final int DIALOG_WARNING_MODIFY = 101;
	  public static final int DIAL_DIALOG = 10;
	  public static final int DIAL_PHONENUMBER = 70004;
	  public static final int DIAL_WEBSITE = 70003;
	  public static final String EPG_SERVICE_URL = "http://wepg.huagu.com";
	  public static final String FINANCIAL_FLOW_LOGIN_INFO = "以L2数据为基础，对市场资金流向进行统计和实时监控，找出受到市场资金重点关注的个股和板块。提供多个周期的板块和个股实时监控。可查看沪深A股及各行业当日、3天、5天、10天、20天资金流入流出情况,及成交大小资金的分布情况，并图形化显示，便于投资人观察一段时间内大资金的异动，主力增减仓的态度，查询各大板块资金进出，寻找当前的市场热点。";
	  public static final String FINANCIAL_FLOW_NAME = "资金流向";
	  public static final String FINANCIAL_REPORT = "http://wepg.huagu.com/epg/hqList.do";
	  public static final String FORCE_UPGRADE = "2";
	  public static final String FORGET_PWD_URL = "http://w3a.huagu.com/smp/self/getpwd.do";
	  public static final String FROM_LEVEL2_TO_PURCHASE = "level2";
	  public static final String FROM_NOTIFICATION_TO_PURCHASE = "notification";
	  public static final String FROM_STOCK_POOL_TO_PURCHASE = "stockPool";
	  public static final String FROM_USER_CENTER_TO_PURCHASE = "userCenter";
	  public static final String HOST_hq = "http://221.130.185.148:2006/Quote.dll?USER=XUYJ";
	  public static final String HOST_hq_Z = "http://221.130.185.148:2006/QuoteZ.dll?USER=XUYJ";
	  public static final String HOTSTOCK_JGGD_NAME = "机构观点";
	  public static final String HOTSTOCK_JGGD_URL = "http://wepg.huagu.com/epg/institutionPoint.do";
	  public static final String HQ_BASE_URL = "http://wds.huagu.com";
	  public static final String HQ_BASE_URL_F5_IP_PORT = "http://wds.huagu.com";
	  public static final String HQ_BASE_URL_IP_PORT = "http://221.130.185.176:80";
	  public static final String HQ_MY_STOCK_LIST = "http://wps.huagu.com/smp/self/stocklist.do";
	  public static final String HQ_OPER_MY_STOCK = "http://wps.huagu.com/smp/self/operstock.do";
	  public static final String HQ_QUERY_MY_ALERT = "http://wps.huagu.com/smp/self/queryalert.do";
	  public static final String HQ_SET_MY_ALERT = "http://wps.huagu.com/smp/self/setalert.do";
	  public static final String HUAGU_LOGIN_INFO = "由华股评测专家团队提供的极具价值的资讯内容。";
	  public static final String HUAGU_MODEL_NAME = "华股内参";
	  public static final String INCREASE_FIFTYTWO_DAYS = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/increase52weekTop10.xml";
	  public static final int INFO_ERROR = 50002;
	  public static final int INFO_REPEAT = 50001;
	  public static final String INSCREASE_FIVE_DAYS = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/increase5dayTop10.xml";
	  public static final int KLINE_COUNT = 110;
	  public static final int KLINE_CYCLE_DIALOG = 10;
	  public static final String[] KLINE_CYCLE_NAMES = {};
	  public static final int KLINE_PAINT_SIZE = 16;
	  public static final int L2_TECHNICAL_INDEX_DIALOG = 24;
	  public static final String[] L2_TECHNICAL_INDEX_NAMES = {};
	  public static final String LOGIN_URL = "http://w3a.huagu.com/smp/pub/loginauth.do";
	  public static final String MAIL_BOX_NAME = "我的信箱";
	  public static final String MAIL_BOX_PATH = "http://wepg.huagu.com/epg/channel.do?channelid=1141";
	  public static final int MARKET_AUTO_REFRESH_ON = 10000;
	  public static final String MARKET_CODE = "0|000001,1|399001,1|399005,0|000300,1|399106,0|000010,0|000016,0|000002,1|399107,0|000003,1|399108,0|000011,1|399305,1|399006,1|399002,1|399003";
	  public static final String MARKET_LIST_NAME = "实时行情";
	  public static final String MARKET_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ";
	  public static final String MARKET_URL_Z = "http://wds.huagu.com/QuoteZ.dll?USER=XUYJ";
	  public static final int MESSAGE_PUSH_HUAGU = 7;
	  public static final String MESSAGE_PUSH_IDS = "20,141,7";
	  public static final int MESSAGE_PUSH_MY_MAILBOX = 141;
	  public static final int MESSAGE_PUSH_MY_PUSH = 20;
	  public static final String MESSAGE_PUSH_SERVICE_URL = "http://wmsg.huagu.com";
	  public static final String MESSAGE_PUSH_URL = "http://wmsg.huagu.com/smp/self/pushinfo.do";
	  public static final String MODIFY_PASSWORD_LOGIN_INFO = "此功能需用户登录后方能使用，已注册用户可直接登录；未注册用户需先注册。";
	  public static final String MODIFY_PASSWORD_NAME = "修改密码";
	  public static final String MOD_PWD_URL = "http://w3a.huagu.com/smp/self/modifypwd.do";
	  public static final String MONEY_STOCK_LEFT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/zldxjr.xml";
	  public static final String MONEY_STOCK_RIGHT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/zlzxyd.xml";
	  public static final String MY_ACCOUNT_LIST = "http://wps.huagu.com/smp/self/myproduct.do";
	  public static final String MY_INFO = "http://wepg.huagu.com/epg/myInfoList.do";
	  public static final String MY_STOCK_LIST_NAME = "我的自选";
	  public static final String MY_WARNING_LOGIN_INFO = "股票价格免费短信预警，注册用户赠送30条免费预警短信。当股价达到用户设定的价位时，系统会发送短信进行预警，帮助用户把握个股操作时机，使用户无论身在何地都可完成对个股的监控与关注。";
	  public static final String MY_WARNING_NAME = "我的预警";
	  public static boolean NEWS_HAS_CLICK_NEXTORPRE = false;
	  public static final String NEWS_HUA_GU_NAME = "华股内参";
	  public static final String NEWS_HUA_GU_URL = "http://wepg.huagu.com/epg/channel.do?channelid=1136";
	  public static final String NEWS_MY_INFO_NAME = "我的资讯";
	  public static final int NONE_DIALOG = 255;
	  public static final int NOTICE_DIALOG = 15;
	  public static final String ONE_BY_ONE_PRODUCT_CODE = "3000";
	  public static final int PANKOU_TEXT_SIZE = 12;
	  public static final String PATH_ZXG_MINI_HQ_HEAD = "?CMD=ZXG_MINI&CODE=";
	  public static final String PKG = "com.dayingjia.stock.activity";
	  public static final String PLATE_MONITOR_DETAIL_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/pm/CFG/";
	  public static final String PLATE_MONITOR_LIST_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/block.xml";
	  public static final int POOL_TIME = 590000;
	  public static final String PRODUCT_INFO_URL = "http://wepg.huagu.com/epg/channel.do?channelid=1140";
	  public static final String PRODUCT_INTRO = "http://wepg.huagu.com/epg/program.do?programid=469405&channelid=1140&forder=20111212";
	  public static final String PRODUCT_SERVICE_URL = "http://wps.huagu.com";
	  public static final String PURCHASE_ROLE = "3";
	  public static final int PURCHASE_TEXT_SIZE = 14;
	  public static final int QUITE_DIALOG = 6;
	  public static final String REGISTER_ROLE = "2";
	  public static final String REGISTER_URL = "http://w3a.huagu.com/smp/self/regist.do";
	  public static final String RELATIVE_INFO_URL = "http://wepg.huagu.com/epg/relativeInfoList.do?stockCode=";
	  public static final String RELAVIVE_INFO_NAME = "相关资讯";
	  public static final String RISK_PROTOCOL = "http://wepg.huagu.com/epg/program.do?programid=469406&channelid=1140&forder=20111212";
	  public static final String RISK_PROTOCOL_NAME = "风险协议";
	  public static final String SEARCH_POOL_PRODUCT_CODE = "3010";
	  public static final String SECTIONMONITOR_PATH = "/fm/block.xml";
	  public static final String SELL_BUY_TI_LINE = "买卖总量";
	  public static final String STOCK_DIAGINOSIS = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/ToptenWeek.xml";
	  public static final String SUCCESS_CODE = "0";
	  public static final String SUMMARY_CATEGORY_BASE = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;";
	  public static final String SUMMARY_CONSISTENT_UP_DAYS = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/riseTop10.xml";
	  public static final String TECENT_ACCESS_URL = "http://open.t.qq.com/cgi-bin/access_token";
	  public static final String TECENT_AUTHORIZE_URL = "http://open.t.qq.com/cgi-bin/authorize";
	  public static final String TECENT_CONSUMER_KEY = "801059963";
	  public static final String TECENT_CONSUMER_SECRET = "e6e793c0d47df9dd934d8bd5bae1f8ae";
	  public static final String TECENT_ENCODING = "UTF-8";
	  public static final String TECENT_OAUTH_CALLBACK_URL = "x-oauthflow://callback";
	  public static final String TECENT_REQUEST_URL = "http://open.t.qq.com/cgi-bin/request_token";
	  public static final int TECHNICAL_INDEX_DIALOG = 13;
	  public static final String[] TECHNICAL_INDEX_NAMES ={} ;
	  public static final String TECH_STOCK_BOLL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/boll.xml";
	  public static final String TECH_STOCK_KDJ = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/kdj.xml";
	  public static final String TECH_STOCK_MACD = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/macd.xml";
	  public static final String TEN_HANDICAP_PRODUCT_CODE = "2040";
	  public static final int TIMELINE_INDEX_DIALOG = 55;
	  public static final int TIMELINE_INDEX_DIALOG2 = 56;
	  public static final String[] TIMELINE_INDEX_NAMES = {};
	  public static final String[] TIMELINE_STOCK_AB_NAMES = {};
	  public static final String[] TIMELINE_STOCK_SZ_NAMES = {};
	  public static final String TIP_UPGRADE = "1";
	  public static final int TOAST_TEXT_SIZE = 27;
	  public static final float TOTAL_MINUTE_LINE_NUMBER = 242.0F;
	  public static final String TURNOVERRATE_FIVE_DAYS = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/turnoverRate5dayTop10.xml";
	  public static final String TURNOVER_SIX_MONTHS = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/turnoverRate6MonthTop10.xml";
	  public static final String USERNAME_PWD_ERROR = "10011";
	  public static final String USER_CENTER_PURCHASE = "http://wps.huagu.com/smp/self/productinfo.do";
	  public static final String USER_LOGIN_NAME = "用户登录";
	  public static final String USER_MODIFY_PASSWORD = "您还未登录，请先登录，再进行密码修改。";
	  public static final String USER_PURCHASE_NAME = "用户购买";
	  public static final String USER_REGISTER_NAME = "用户注册";
	  public static final String VALUE_STOCK_LEFT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/jzcz.xml";
	  public static final String VALUE_STOCK_RIGHT = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/jgzx.xml";
	  public static final String VISITOR_ROLE = "1";
	  public static final String WARNING_MODIFY_URL = "http://wds.huagu.com/smp/self/setalert.do";
	  public static final String WARNING_QUERY_URL = "http://wds.huagu.com/smp/self/queryalert.do";
	  public static final int WEIBO_AUTHENTICATION = 12;
	  public static final int WEIBO_MAX_LENGTH = 140;
	  public static final String WINDATA_LOGIN_INFO = "华股打造的统一的金融数据服务品牌，依托上交所、深交所的海量实时行情数据和华股强大的特色资讯体系及广泛的第三方数据提供商、金融分析模型处理优势，为用户提供实时、高效、准确的金融数据增值服务。功能有拖拉机单统计、资金流向、大单分析、准赢股票池等。";
	  public static final String WINDATA_MODEL_NAME = "准赢数据";
	  public static final int WIN_DATA_GOLDEN_POOL_TYPE = 1;
	  public static final String WIN_DATA_GOLDEN_STOCK_POOL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/doctordata.xml";
	  public static final int WIN_DATA_LEVEL_ID = 4;
	  public static final int WIN_DATA_SEARCH_POOL_TYPE = 2;
	  public static final String WIN_DATA_SEARCH_STOCK_POOL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=MFTP&amp;/fm/CodeList.xml";
	  public static final String[] XDS = {};
	  public static final int XD_DIALOG = 21;
	  public static final String XINLANG_ACCESS_URL = "http://api.t.sina.com.cn/oauth/access_token";
	  public static final String XINLANG_AUTHORIZE_URL = "http://api.t.sina.com.cn/oauth/authorize";
	  public static final String XINLANG_CONSUMER_KEY = "609231728";
	  public static final String XINLANG_CONSUMER_SECRET = "3380c96417b1d073a2148b08a360338a";
	  public static final String XINLANG_ENCODING = "UTF-8";
	  public static final String XINLANG_OAUTH_CALLBACK_URL = "x-oauthflow://callback";
	  public static final String XINLANG_REQUEST_URL = "http://api.t.sina.com.cn/oauth/request_token";
	  public static final String ZXG_SORT_DM = "代码";
	  public static final String ZXG_SORT_HS = "换手";
	  public static final String ZXG_SORT_LB = "量比";
	  public static final String ZXG_SORT_XJ = "现价";
	  public static final String ZXG_SORT_ZD = "涨跌";
	  public static final String ZXG_SORT_ZE = "总额";
	  public static final String ZXG_SORT_ZF = "涨幅";
	  public static final String ZXG_SORT_ZG = "最高";
	  public static final String ZXG_SORT_ZHENF = "振幅";
	  public static final String ZXG_SORT_ZS = "总手";
	  public static final String ZXG_SORT_ZUID = "最低";
	  public static final String ZXG_SORT_ZUOS = "昨收";
	  public static final String ZXG_URL = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=ZXG&amp;CODE=";
	  public static int autoRefreshTime = 0;
	  public static final String[] bigDataName = {};
	  public static final String[] categoryRankingArray = {};
	  public static final String[] categoryRankingSort = {};
	  public static final String[][] paths = {};
	  public static boolean retryCanceled = false;
	  public static final int retryTimes = 3;
	//  public static final String[][] sListContents;
	  public static final String[] sMarketNames;
	  public static final String[] sortColumName;
	  public static final int[] sortType;
	  public static final String[] tuolaShName;

	  static
	  {
	    autoRefreshTime = 6000;
	    NEWS_HAS_CLICK_NEXTORPRE = false;
	    String[] arrayOfString1 = new String[13];
	    arrayOfString1[0] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=1|";
	    arrayOfString1[1] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=2|";
	    arrayOfString1[2] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=3|";
	    arrayOfString1[3] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=4|";
	    arrayOfString1[4] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=5|";
	    arrayOfString1[5] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=14|";
	    arrayOfString1[6] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=16|";
	    arrayOfString1[7] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=6|";
	    arrayOfString1[8] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=10|";
	    arrayOfString1[9] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=11|";
	    arrayOfString1[10] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=7|";
	    arrayOfString1[11] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=8|";
	    arrayOfString1[12] = "http://wds.huagu.com/Quote.dll?USER=XUYJ?CMD=SORT&amp;CODE=15|";
	    //categoryRankingArray = arrayOfString1;
	    String[] arrayOfString2 = new String[7];
	    arrayOfString2[0] = "涨幅";
	    arrayOfString2[1] = "跌幅";
	    arrayOfString2[2] = "总手";
	    arrayOfString2[3] = "总额";
	    arrayOfString2[4] = "换手";
	    arrayOfString2[5] = "量比";
	    arrayOfString2[6] = "振幅";
	    //categoryRankingSort = arrayOfString2;
	    sortType = new int[] { 2, 3, 4, 6, 10, 7, 8 };
	    String[] arrayOfString3 = new String[11];
	    arrayOfString3[0] = "现价";
	    arrayOfString3[1] = "涨幅";
	    arrayOfString3[2] = "涨跌";
	    arrayOfString3[3] = "昨收";
	    arrayOfString3[4] = "总手";
	    arrayOfString3[5] = "总额";
	    arrayOfString3[6] = "最高";
	    arrayOfString3[7] = "最低";
	    arrayOfString3[8] = "换手";
	    arrayOfString3[9] = "量比";
	    arrayOfString3[10] = "振幅";
	    sortColumName = arrayOfString3;
	    String[] arrayOfString4 = new String[7];
	    arrayOfString4[0] = "当日大单动能";
	    arrayOfString4[1] = "3日大单动能";
	    arrayOfString4[2] = "5日大单动能";
	    arrayOfString4[3] = "10 日大单动能";
	    arrayOfString4[4] = "大单连续买入天数";
	    arrayOfString4[5] = "当日大买单比";
	    arrayOfString4[6] = "当日大卖单比 ";
	    //bigDataName = arrayOfString4;
	    String[] arrayOfString5 = new String[3];
	    arrayOfString5[0] = "当日";
	    arrayOfString5[1] = "最近3日";
	    arrayOfString5[2] = "最近5日";
	    tuolaShName = arrayOfString5;
	    String[] arrayOfString6 = new String[4];
	    arrayOfString6[0] = "上证A股";
	    arrayOfString6[1] = "上证B股";
	    arrayOfString6[2] = "深证A股";
	    arrayOfString6[3] = "深证B股";
	    sMarketNames = arrayOfString6;
	    String[] arrayOfString7 = new String[4];
	    String[] arrayOfString8 = new String[12];
	    arrayOfString8[0] = "涨幅前10";
	    arrayOfString8[1] = "跌幅前10";
	    arrayOfString8[2] = "5分钟涨速前10";
	    arrayOfString8[3] = "5分钟跌速前10";
	    arrayOfString8[4] = "总金额前10";
	    arrayOfString8[5] = "成交价前10";
	    arrayOfString8[6] = "成交价后10";
	    arrayOfString8[7] = "量比前10";
	    arrayOfString8[8] = "振幅前10";
	    arrayOfString8[9] = "委比前10";
	    arrayOfString8[10] = "委比后10";
	    arrayOfString8[11] = "换手率前10";
	    arrayOfString7[0] = arrayOfString8[0];
	    String[] arrayOfString9 = new String[12];
	    arrayOfString9[0] = "涨幅前10";
	    arrayOfString9[1] = "跌幅前10";
	    arrayOfString9[2] = "5分钟涨速前10";
	    arrayOfString9[3] = "5分钟跌速前10";
	    arrayOfString9[4] = "总金额前10";
	    arrayOfString9[5] = "成交价前10";
	    arrayOfString9[6] = "成交价后10";
	    arrayOfString9[7] = "量比前10";
	    arrayOfString9[8] = "振幅前10";
	    arrayOfString9[9] = "委比前10";
	    arrayOfString9[10] = "委比后10";
	    arrayOfString9[11] = "换手率前10";
	    arrayOfString7[1] = arrayOfString9[0];
	    String[] arrayOfString10 = new String[12];
	    arrayOfString10[0] = "涨幅前10";
	    arrayOfString10[1] = "跌幅前10";
	    arrayOfString10[2] = "5分钟涨速前10";
	    arrayOfString10[3] = "5分钟跌速前10";
	    arrayOfString10[4] = "总金额前10";
	    arrayOfString10[5] = "成交价前10";
	    arrayOfString10[6] = "成交价后10";
	    arrayOfString10[7] = "量比前10";
	    arrayOfString10[8] = "振幅前10";
	    arrayOfString10[9] = "委比前10";
	    arrayOfString10[10] = "委比后10";
	    arrayOfString10[11] = "换手率前10";
	    arrayOfString7[2] = arrayOfString10[0];
	    String[] arrayOfString11 = new String[12];
	    arrayOfString11[0] = "涨幅前10";
	    arrayOfString11[1] = "跌幅前10";
	    arrayOfString11[2] = "5分钟涨速前10";
	    arrayOfString11[3] = "5分钟跌速前10";
	    arrayOfString11[4] = "总金额前10";
	    arrayOfString11[5] = "成交价前10";
	    arrayOfString11[6] = "成交价后10";
	    arrayOfString11[7] = "量比前10";
	    arrayOfString11[8] = "振幅前10";
	    arrayOfString11[9] = "委比前10";
	    arrayOfString11[10] = "委比后10";
	    arrayOfString11[11] = "换手率前10";
	    arrayOfString7[3] = arrayOfString11[0];
	    //sListContents = arrayOfString7;
	    String[] arrayOfString12 = new String[4];
	    String[] arrayOfString13 = new String[12];
	    arrayOfString13[0] = "/fm/shag_up10.xml";
	    arrayOfString13[1] = "/fm/shag_dn10.xml";
	    arrayOfString13[2] = "/fm/shag_zsup10.xml";
	    arrayOfString13[3] = "/fm/shag_zsdn10.xml";
	    arrayOfString13[4] = "/fm/shag_cjeup10.xml";
	    arrayOfString13[5] = "/fm/shag_xjup10.xml";
	    arrayOfString13[6] = "/fm/shag_xjdn10.xml";
	    arrayOfString13[7] = "/fm/shag_lbup10.xml";
	    arrayOfString13[8] = "/fm/shag_zfup10.xml";
	    arrayOfString13[9] = "/fm/shag_wbup10.xml";
	    arrayOfString13[10] = "/fm/shag_wbdn10.xml";
	    arrayOfString13[11] = "/fm/shag_hsup10.xml";
	    //arrayOfString12[0] = arrayOfString13;
	    String[] arrayOfString14 = new String[12];
	    arrayOfString14[0] = "/fm/shbg_up10.xml";
	    arrayOfString14[1] = "/fm/shbg_dn10.xml";
	    arrayOfString14[2] = "/fm/shbg_zsup10.xml";
	    arrayOfString14[3] = "/fm/shbg_zsdn10.xml";
	    arrayOfString14[4] = "/fm/shbg_cjeup10.xml";
	    arrayOfString14[5] = "/fm/shbg_xjup10.xml";
	    arrayOfString14[6] = "/fm/shbg_xjdn10.xml";
	    arrayOfString14[7] = "/fm/shbg_lbup10.xml";
	    arrayOfString14[8] = "/fm/shbg_zfup10.xml";
	    arrayOfString14[9] = "/fm/shbg_wbup10.xml";
	    arrayOfString14[10] = "/fm/shbg_wbdn10.xml";
	    arrayOfString14[11] = "/fm/shbg_hsup10.xml";
	    //arrayOfString12[1] = arrayOfString14;
	    String[] arrayOfString15 = new String[12];
	    arrayOfString15[0] = "/fm/szag_up10.xml";
	    arrayOfString15[1] = "/fm/szag_dn10.xml";
	    arrayOfString15[2] = "/fm/szag_zsup10.xml";
	    arrayOfString15[3] = "/fm/szag_zsdn10.xml";
	    arrayOfString15[4] = "/fm/szag_cjeup10.xml";
	    arrayOfString15[5] = "/fm/szag_xjup10.xml";
	    arrayOfString15[6] = "/fm/szag_xjdn10.xml";
	    arrayOfString15[7] = "/fm/szag_lbup10.xml";
	    arrayOfString15[8] = "/fm/szag_zfup10.xml";
	    arrayOfString15[9] = "/fm/szag_wbup10.xml";
	    arrayOfString15[10] = "/fm/szag_wbdn10.xml";
	    arrayOfString15[11] = "/fm/szag_hsup10.xml";
	    //arrayOfString12[2] = arrayOfString15;
	    String[] arrayOfString16 = new String[12];
	    arrayOfString16[0] = "/fm/szbg_up10.xml";
	    arrayOfString16[1] = "/fm/szbg_dn10.xml";
	    arrayOfString16[2] = "/fm/szbg_zsup10.xml";
	    arrayOfString16[3] = "/fm/szbg_zsdn10.xml";
	    arrayOfString16[4] = "/fm/szbg_cjeup10.xml";
	    arrayOfString16[5] = "/fm/szbg_xjup10.xml";
	    arrayOfString16[6] = "/fm/szbg_xjdn10.xml";
	    arrayOfString16[7] = "/fm/szbg_lbup10.xml";
	    arrayOfString16[8] = "/fm/szbg_zfup10.xml";
	    arrayOfString16[9] = "/fm/szbg_wbup10.xml";
	    arrayOfString16[10] = "/fm/szbg_wbdn10.xml";
	    arrayOfString16[11] = "/fm/szbg_hsup10.xml";
	    //arrayOfString12[3] = arrayOfString16;
	    //paths = arrayOfString12;
	    String[] arrayOfString17 = new String[7];
	    arrayOfString17[0] = "五分钟";
	    arrayOfString17[1] = "十五分钟";
	    arrayOfString17[2] = "三十分钟";
	    arrayOfString17[3] = "六十分钟";
	    arrayOfString17[4] = "日线";
	    arrayOfString17[5] = "周线";
	    arrayOfString17[6] = "月线";
	    //KLINE_CYCLE_NAMES = arrayOfString17;
	    String[] arrayOfString18 = new String[3];
	    arrayOfString18[0] = "分时量";
	    arrayOfString18[1] = "买卖总量";
	    arrayOfString18[2] = "涨跌家数";
	    //TIMELINE_INDEX_NAMES = arrayOfString18;
	    String[] arrayOfString19 = new String[3];
	    arrayOfString19[0] = "分时量";
	    arrayOfString19[1] = "量比";
	    arrayOfString19[2] = "买卖总量";
	    //TIMELINE_STOCK_AB_NAMES = arrayOfString19;
	    String[] arrayOfString20 = new String[2];
	    arrayOfString20[0] = "分时量";
	    arrayOfString20[1] = "量比";
	    //TIMELINE_STOCK_SZ_NAMES = arrayOfString20;
	    String[] arrayOfString21 = new String[6];
	    arrayOfString21[0] = "VOL";
	    arrayOfString21[1] = "MACD";
	    arrayOfString21[2] = "RSI";
	    arrayOfString21[3] = "WR";
	    arrayOfString21[4] = "KDJ";
	    arrayOfString21[5] = "BOLL";
	    //TECHNICAL_INDEX_NAMES = arrayOfString21;
	    String[] arrayOfString22 = new String[10];
	    arrayOfString22[0] = "DDX";
	    arrayOfString22[1] = "DDY";
	    arrayOfString22[2] = "DDZ";
	    arrayOfString22[3] = "大单动能";
	    arrayOfString22[4] = "大单量差";
	    arrayOfString22[5] = "大单买入";
	    arrayOfString22[6] = "大单卖出";
	    arrayOfString22[7] = "累计大单";
	    arrayOfString22[8] = "主力持仓";
	    arrayOfString22[9] = "散户线";
	    //L2_TECHNICAL_INDEX_NAMES = arrayOfString22;
	    String[] arrayOfString23 = new String[3];
	    arrayOfString23[0] = "前复权";
	    arrayOfString23[1] = "后复权";
	    arrayOfString23[2] = "不复权";
	  }
}
